const diem_sv = [
    {
      id: "MVC106",
      sbd: "001",
      name: "Ngô Thị Hồng Nhung",
      Khoi_thi: "D01",
      Mon_1: "Văn",
      Mon_2: "Toán",
      Mon_3: "Anh",
      Diem_1: 9,
      Diem_2: 8.8,
      Diem_3: 7,
    },
    {
      id: "MVC401",
      sbd: "001",
      name: "Ngô Thị Hồng Nhung",
      Khoi_thi: "D01",
      Mon_1: "Văn",
      Mon_2: "Toán",
      Mon_3: "Anh",
      Diem_1: 9,
      Diem_2: 8.8,
      Diem_3: 7,
    },
    {
      id: "MVC119",
      sbd: "002",
      name: "Đỗ Hồng Ngọc",
      Khoi_thi: "B00",
      Mon_1: "Toán",
      Mon_2: "Sinh",
      Mon_3: "Hóa",
      Diem_1: 3,
      Diem_2: 3.5,
      Diem_3: 3,
    },
    {
      id: "MVC118",
      sbd: "002",
      name: "Đỗ Hồng Ngọc",
      Khoi_thi: "A00",
      Mon_1: "Toán",
      Mon_2: "Lý",
      Mon_3: "Hóa",
      Diem_1: 3,
      Diem_2: 3.5,
      Diem_3: 3.2,
    },
    {
      id: "MVC110",
      sbd: "003",
      name: "Hoàng Thị Minh Lan",
      Khoi_thi: "A01",
      Mon_1: "Toán",
      Mon_2: "Lý",
      Mon_3: "Anh",
      Diem_1: 7,
      Diem_2: 8.5,
      Diem_3: 6.4,
    },
    {
      id: "MVC107",
      sbd: "003",
      name: "Hoàng Thị Minh Lan",
      Khoi_thi: "A00",
      Mon_1: "Toán",
      Mon_2: "Lý",
      Mon_3: "Hóa",
      Diem_1: 7,
      Diem_2: 9,
      Diem_3: 8.5,
    },
    {
      id: "MVC105",
      sbd: "004",
      name: "Đỗ Minh Hùng",
      Khoi_thi: "D07",
      Mon_1: "Toán",
      Mon_2: "Hóa",
      Mon_3: "Anh",
      Diem_1: 8.4,
      Diem_2: 7,
      Diem_3: 6,
    },
    {
      id: "MVC106",
      sbd: "005",
      name: "Đỗ Ngọc Minh",
      Khoi_thi: "A00",
      Mon_1: "Toán",
      Mon_2: "Lý",
      Mon_3: "Hóa",
      Diem_1: 7.2,
      Diem_2: 8,
      Diem_3: 7,
    },
    {
      id: "MVC121",
      sbd: "006",
      name: "Hoàng Thị May",
      Khoi_thi: "D01",
      Mon_1: "Văn",
      Mon_2: "Toán",
      Mon_3: "Anh",
      Diem_1: 7,
      Diem_2: 6,
      Diem_3: 9,
    },
    {
      id: "MVC401",
      sbd: "007",
      name: "Tòng Thị Hoàng",
      Khoi_thi: "D01",
      Mon_1: "Văn",
      Mon_2: "Toán",
      Mon_3: "Anh",
      Diem_1: 2.5,
      Diem_2: 3.4,
      Diem_3: 4,
    },
    {
      id: "MVC114",
      sbd: "007",
      name: "Tòng Thị Hoàng",
      Khoi_thi: "D01",
      Mon_1: "Văn",
      Mon_2: "Toán",
      Mon_3: "Anh",
      Diem_1: 2.5,
      Diem_2: 3.4,
      Diem_3: 4,
    },
    {
      id: "MVC120",
      sbd: "008",
      name: "Nguyễn Ánh Nguyệt",
      Khoi_thi: "A00",
      Mon_1: "Toán",
      Mon_2: "Lý",
      Mon_3: "Hóa",
      Diem_1: 9.2,
      Diem_2: 8,
      Diem_3: 8.2,
    },
    {
      id: "MVC402",
      sbd: "009",
      name: "Uông Văn Nam",
      Khoi_thi: "A01",
      Mon_1: "Toán",
      Mon_2: "Lý",
      Mon_3: "Anh",
      Diem_1: 7,
      Diem_2: 6,
      Diem_3: 9,
    },
    {
      id: "MVC112",
      sbd: "009",
      name: "Uông Văn Nam",
      Khoi_thi: "A00",
      Mon_1: "Toán",
      Mon_2: "Lý",
      Mon_3: "Hóa",
      Diem_1: 7,
      Diem_2: 6,
      Diem_3: 7,
    },
    {
      id: "MVC123",
      sbd: "010",
      name: "Nguyễn Khánh Linh",
      Khoi_thi: "D07",
      Mon_1: "Toán",
      Mon_2: "Hóa",
      Mon_3: "Anh",
      Diem_1: 8.4,
      Diem_2: 6.5,
      Diem_3: 7,
    },
    {
      id: "MVC105",
      sbd: "011",
      name: "Hoàng Hải Long",
      Khoi_thi: "A00",
      Mon_1: "Toán",
      Mon_2: "Lý",
      Mon_3: "Hóa",
      Diem_1: 7,
      Diem_2: 6,
      Diem_3: 8,
    },
    {
      id: "MVC401",
      sbd: "012",
      name: "Ngô Hải Minh",
      Khoi_thi: "D01",
      Mon_1: "Văn",
      Mon_2: "Toán",
      Mon_3: "Anh",
      Diem_1: 5,
      Diem_2: 7,
      Diem_3: 5,
    },
    {
      id: "MVC118",
      sbd: "012",
      name: "Ngô Hải Minh",
      Khoi_thi: "D08",
      Mon_1: "Toán",
      Mon_2: "Sinh",
      Mon_3: "Anh",
      Diem_1: 7,
      Diem_2: 3.5,
      Diem_3: 5,
    },
  ];

const search_table = document.getElementById("table_list");
const search_sbd = document.getElementById("sbd");
search_sbd.onchange = () => {
    var search_list = diem_sv.map(item => {
        if(search_sbd.value == item.sbd) {
            return `
            <tr class="table_row">
            <td>${item.sbd}</td>
            <td>${item.name}</td>
            <td>${item.id}</td>
            <td>${item.Khoi_thi}</td>
            <td>${item.Diem_1}</td>
            <td>${item.Diem_2}</td>
            <td>${item.Diem_3}</td>
            </tr>
            `
        }
    }).join('');
    search_table.innerHTML = search_list
}